apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment-blue
  labels:
    app: capstone-project-cloud-devops
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project-cloud-devops
  template:
    metadata:
      labels:
        app: capstone-project-cloud-devops
        role: blue
    spec:
      containers:
        - image: vinothramesh/blue-app:latest
          imagePullPolicy: Always
          name: blue-app
          ports:
            - containerPort: 5000
