apiVersion: v1
kind: Service
metadata:
  name: capstone-service-blue
  labels:
    app: capstone-project-cloud-devops
    role: blue
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-cloud-devops
    role: blue
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 5000